import timer from './modules/timer';
import menu from './modules/menu';
import modal from './modules/modal';
import forms from './modules/forms';
import tabs from './modules/tabs';
timer('25 august 2024');
menu();
modal();
forms();
tabs();
