import timer from './modules/timer';
import menu from './modules/menu';
import modal from './modules/modal';
import forms from './modules/forms';
import tabs from './modules/tabs';
import slider from './modules/slider';
import sliderCarousel from './modules/sliderCarousel';
import calc from './modules/calc';
timer('25 august 2024');
menu();
modal();
forms();
tabs();
slider();
sliderCarousel();
calc(100);
